name: BlueMap-PlaceholderNames
version: "${version}"
main: codes.antti.bluemap.placeholdernames.BlueMapPlaceholderNamesSpigot
description: Use placeholder templates for BlueMap player names.
api-version: "${minecraft_version}"
depend: [BlueMap, PlaceholderAPI]
